// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUa-dooe_iCLXqiU1bCqpjVmwTUYbnSFc',
    appId: '1:29983992876:web:83936324f1d2f5bc047589',
    messagingSenderId: '29983992876',
    projectId: 'motion-detector-new',
    authDomain: 'motion-detector-new.firebaseapp.com',
    storageBucket: 'motion-detector-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYG-xB-vmKvgNHIkMHOSGjL3SdnlJgsF0',
    appId: '1:29983992876:android:506040c1a3cf86e5047589',
    messagingSenderId: '29983992876',
    projectId: 'motion-detector-new',
    storageBucket: 'motion-detector-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXpMAYPd04diHOvMD6T-AgT9Hdx40k6Q',
    appId: '1:29983992876:ios:1356658fcf0d1359047589',
    messagingSenderId: '29983992876',
    projectId: 'motion-detector-new',
    storageBucket: 'motion-detector-new.appspot.com',
    iosClientId: '29983992876-o8tiuseseol461goeho2ko86iae4d3hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlXpMAYPd04diHOvMD6T-AgT9Hdx40k6Q',
    appId: '1:29983992876:ios:c0c728859b268f6b047589',
    messagingSenderId: '29983992876',
    projectId: 'motion-detector-new',
    storageBucket: 'motion-detector-new.appspot.com',
    iosClientId: '29983992876-5laurnoissvmnsrkqrq29vq8p87u811k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
